export const state = {
    tables: [],
    selectedTable: null,
    hoveredTable: null,
    mode: 'select',
    nextTableNumber: 1,
    canvasScale: 1,
    canvasOffsetX: 0,
    canvasOffsetY: 0,
    isPanning: false,
    panLastX: 0,
    panLastY: 0,
    isDragging: false,
    dragOffsetX: 0,
    dragOffsetY: 0,
    alignmentLine: null,
    currentUser: null,
    currentUserData: null,
};
